import newyork from "../images/new-york/new-york-logo.png";
import orlando from "../images/orlando/orlando-logo.jpg";
import stlouis from "../images/st-louis/st-louis-logo.jpeg";
import mtrush from "../images/mt-rush/mt-rush-logo.jpg";
import sanfran from "../images/san-fran/san-fran-logo.avif";

const places = [
  {
    // city: "",
    // state: "",
    // landmark: "",
    // latitude: "",
    // longitude: "",
    // type: "",
    // visitTimeHrs: "",
    // averageUserRating: "",
    // popularity: "",
    // visitors: "",
    name: "New York",
    route: "/new-york",
    image: newyork,
    className: "map__ny-logo",
  },
  {
    // city: "",
    // state: "",
    // landmark: "",
    // latitude: "",
    // longitude: "",
    // type: "",
    // visitTimeHrs: "",
    // averageUserRating: "",
    // popularity: "",
    // visitors: "",
    name: "Orlando",
    route: "/orlando",
    image: orlando,
    className: "map__orlando-logo",
  },
  {
    // city: "",
    // state: "",
    // landmark: "",
    // latitude: "",
    // longitude: "",
    // type: "",
    // visitTimeHrs: "",
    // averageUserRating: "",
    // popularity: "",
    // visitors: "",
    name: "St. Louis",
    route: "/st-louis",
    image: stlouis,
    className: "map__st-logo",
  },
  {
    // city: "",
    // state: "",
    // landmark: "",
    // latitude: "",
    // longitude: "",
    // type: "",
    // visitTimeHrs: "",
    // averageUserRating: "",
    // popularity: "",
    // visitors: "",
    name: "Mt. Rushmore",
    route: "/mt-rushmore",
    image: mtrush,
    className: "map__mt-logo",
  },
  {
    // city: "",
    // state: "",
    // landmark: "",
    // latitude: "",
    // longitude: "",
    // type: "",
    // visitTimeHrs: "",
    // averageUserRating: "",
    // popularity: "",
    // visitors: "",
    name: "San Fransisco",
    route: "/san-fransisco",
    image: sanfran,
    className: "map__sanfran-logo",
  },
];

export { places };
