import newyork from "../images/new-york/new-york-logo.png";
import orlando from "../images/orlando/orlando-logo.jpg";
import stlouis from "../images/st-louis/st-louis-logo.jpeg";
import mtrush from "../images/mt-rush/mt-rush-logo.jpg";
import sanfran from "../images/san-fran/san-fran-logo.avif";

const places = [
  {
    city: "New York",
    state: "New York",
    landmark: "Statue of Liberty",
    latitude: "40.6892",
    longitude: "-74.0445",
    type: "Historical/Architectural",
    visitTimeHrs: "4",
    averageUserRating: "4.7",
    popularity: "30000",
    visitors: "4300000",
    name: "New York",
    route: "/new-york",
    image: newyork,
    className: "map__ny-logo",
  },
  {
    city: "Orlando",
    state: "Florida",
    landmark: "Disney World",
    latitude: "28.3852",
    longitude: "-81.5639",
    type: "Amusement Park",
    visitTimeHrs: "8",
    averageUserRating: "4.7",
    popularity: "85000",
    visitors: "58000000",
    name: "Orlando",
    route: "/orlando",
    image: orlando,
    className: "map__orlando-logo",
  },
  {
    city: "St. Louis",
    state: "Missouri",
    landmark: "Gateway Arch",
    latitude: "38.6247",
    longitude: "-90.1848",
    type: "Architectural",
    visitTimeHrs: "2",
    averageUserRating: "4.7",
    popularity: "15000",
    visitors: "2000000",
    name: "St. Louis",
    route: "/st-louis",
    image: stlouis,
    className: "map__st-logo",
  },
  {
    city: "Keystone",
    state: "South Dakota",
    landmark: "Mount Rushmore",
    latitude: "43.8791",
    longitude: "-103.4591",
    type: "Historical/Architectural",
    visitTimeHrs: "2",
    averageUserRating: "4.7",
    popularity: "25000",
    visitors: "2000000",
    name: "Mt. Rushmore",
    route: "/mt-rushmore",
    image: mtrush,
    className: "map__mt-logo",
  },
  {
    city: "San Francisco",
    state: "California",
    landmark: "Golden Gate Bridge",
    latitude: "37.8199",
    longitude: "-122.4783",
    type: "Architectural",
    visitTimeHrs: "2",
    averageUserRating: "4.8",
    popularity: "45000",
    visitors: "10000000",
    name: "San Fransisco",
    route: "/san-fransisco",
    image: sanfran,
    className: "map__sanfran-logo",
  },
];

export { places };
